src/SAWebHost/Pages/Applications/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LinkedInApiClient;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Applications
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public CreateModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            LinkedInProvider = new LinkedInProvider
            {
                Id = IdGenerator.GetOne("app", Guid.NewGuid())
            };

            return Page();
        }

        [BindProperty]
        public LinkedInProvider LinkedInProvider { get; set; }


        public IActionResult OnPostUseLinkedInSettings()
        {
            if (!ModelState.IsValid)
            {
                ModelState.Clear();
            }

            LinkedInProvider = new LinkedInProvider
            {
                ApplicationName = LinkedInProvider.ApplicationName,
                Id = LinkedInProvider.Id,
                IsActive = LinkedInProvider.IsActive,
                ClientId = LinkedInProvider.ClientId,
                ClientSecret = LinkedInProvider.ClientSecret,
                AuthorizationEndpoint = LinkedInConstants.DefaultAuthorizationEndpoint,
                TokenEndpoint = LinkedInConstants.DefaultTokenEndpoint,
                Scope = "r_organization_social r_1st_connections_size r_ads_reporting rw_organization_admin r_basicprofile r_ads"
            };

            return Page();
        }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.LinkedInProvider.Add(LinkedInProvider);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

src/SAWebHost/Pages/Applications/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Applications
{
    [Authorize]
    public class DeleteModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public DeleteModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        [BindProperty]
        public LinkedInProvider LinkedInProvider { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            LinkedInProvider = await _context.LinkedInProvider.FirstOrDefaultAsync(m => m.Id == id);

            if (LinkedInProvider == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            LinkedInProvider = await _context.LinkedInProvider.FindAsync(id);

            if (LinkedInProvider != null)
            {
                _context.LinkedInProvider.Remove(LinkedInProvider);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

src/SAWebHost/Pages/Applications/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Applications
{
    public class DetailsModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public DetailsModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        public LinkedInProvider LinkedInProvider { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            LinkedInProvider = await _context.LinkedInProvider.FirstOrDefaultAsync(m => m.Id == id);

            if (LinkedInProvider == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

src/SAWebHost/Pages/Applications/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Applications
{
    [Authorize]
    public class EditModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public EditModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        [BindProperty]
        public LinkedInProvider LinkedInProvider { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            LinkedInProvider = await _context.LinkedInProvider.FirstOrDefaultAsync(m => m.Id == id);

            if (LinkedInProvider == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(LinkedInProvider).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LinkedInProviderExists(LinkedInProvider.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool LinkedInProviderExists(string id)
        {
            return _context.LinkedInProvider.Any(e => e.Id == id);
        }
    }
}

src/SAWebHost/Pages/Applications/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Applications
{
    public class IndexModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public IndexModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        public IList<LinkedInProvider> LinkedInProvider { get;set; }

        public async Task OnGetAsync()
        {
            LinkedInProvider = await _context.LinkedInProvider.ToListAsync();
        }
    }
}

src/SAWebHost/Pages/Organizations/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Organizations
{
    public record TableOption
    {
        public int MyProperty { get; set; }
    }

    public class CreateModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public CreateModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            Organization = new Organization
            {
                Id = IdGenerator.GetOne("organization", Guid.NewGuid())
            };

            return Page();
        }

        [BindProperty]
        public Organization Organization { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Organization.Add(Organization);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

src/SAWebHost/Pages/Organizations/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Organizations
{
    [Authorize]
    public class DeleteModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public DeleteModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Organization Organization { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Organization = await _context.Organization.FirstOrDefaultAsync(m => m.Id == id);

            if (Organization == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Organization = await _context.Organization.FindAsync(id);

            if (Organization != null)
            {
                _context.Organization.Remove(Organization);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

src/SAWebHost/Pages/Organizations/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Organizations
{
    public class DetailsModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public DetailsModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        public Organization Organization { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Organization = await _context.Organization.FirstOrDefaultAsync(m => m.Id == id);

            if (Organization == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

src/SAWebHost/Pages/Organizations/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Organizations
{
    [Authorize]
    public class EditModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public EditModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Organization Organization { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Organization = await _context.Organization.FirstOrDefaultAsync(m => m.Id == id);

            if (Organization == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Organization).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrganizationExists(Organization.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool OrganizationExists(string id)
        {
            return _context.Organization.Any(e => e.Id == id);
        }
    }
}

src/SAWebHost/Pages/Tokens/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Tokens
{
    [Authorize]
    public class DeleteModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public DeleteModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        [BindProperty]
        public AccessTokenEntry AccessTokenEntry { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AccessTokenEntry = await _context.AccessTokenEntry.FirstOrDefaultAsync(m => m.Id == id);

            if (AccessTokenEntry == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AccessTokenEntry = await _context.AccessTokenEntry.FindAsync(id);

            if (AccessTokenEntry != null)
            {
                _context.AccessTokenEntry.Remove(AccessTokenEntry);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

src/SAWebHost/Pages/Tokens/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Tokens
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public DetailsModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        public AccessTokenEntry AccessTokenEntry { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AccessTokenEntry = await _context.AccessTokenEntry.FirstOrDefaultAsync(m => m.Id == id);

            if (AccessTokenEntry == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

src/SAWebHost/Pages/Applications/Create.cshtml
@page
@model SAWebHost.Pages.Applications.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>LinkedInProvider</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.Id" class="control-label"></label>
                <input asp-for="LinkedInProvider.Id" class="form-control" readonly />
                <span asp-validation-for="LinkedInProvider.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.ApplicationName" class="control-label"></label>
                <input asp-for="LinkedInProvider.ApplicationName" class="form-control" />
                <span asp-validation-for="LinkedInProvider.ApplicationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.ClientId" class="control-label"></label>
                <input asp-for="LinkedInProvider.ClientId" class="form-control" />
                <span asp-validation-for="LinkedInProvider.ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.ClientSecret" class="control-label"></label>
                <input asp-for="LinkedInProvider.ClientSecret" class="form-control" />
                <span asp-validation-for="LinkedInProvider.ClientSecret" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.AuthorizationEndpoint" class="control-label"></label>
                <input asp-for="LinkedInProvider.AuthorizationEndpoint" class="form-control" />
                <span asp-validation-for="LinkedInProvider.AuthorizationEndpoint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.TokenEndpoint" class="control-label"></label>
                <input asp-for="LinkedInProvider.TokenEndpoint" class="form-control" />
                <span asp-validation-for="LinkedInProvider.TokenEndpoint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.Scope" class="control-label"></label>
                <input asp-for="LinkedInProvider.Scope" class="form-control" />
                <span asp-validation-for="LinkedInProvider.Scope" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="LinkedInProvider.IsActive" /> @Html.DisplayNameFor(model => model.LinkedInProvider.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" asp-page-handler="Create" />
                <input type="submit" value="Use LinkedIn settings" class="btn btn-secondary" formnovalidate asp-page-handler="UseLinkedInSettings"  />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SAWebHost/Pages/Applications/Delete.cshtml
@page
@model SAWebHost.Pages.Applications.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LinkedInProvider</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LinkedInProvider.ApplicationName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LinkedInProvider.ApplicationName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LinkedInProvider.ClientId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LinkedInProvider.ClientId)
        </dd>
 @*       <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LinkedInProvider.ClientSecret)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LinkedInProvider.ClientSecret)
        </dd>*@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LinkedInProvider.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LinkedInProvider.IsActive)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="LinkedInProvider.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

src/SAWebHost/Pages/Applications/Details.cshtml
@page
@model SAWebHost.Pages.Applications.DetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>LinkedInProvider</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LinkedInProvider.ApplicationName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LinkedInProvider.ApplicationName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LinkedInProvider.ClientId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LinkedInProvider.ClientId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LinkedInProvider.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LinkedInProvider.IsActive)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.LinkedInProvider.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

src/SAWebHost/Pages/Applications/Edit.cshtml
@page
@model SAWebHost.Pages.Applications.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>LinkedInProvider</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LinkedInProvider.Id" />
            <div class="form-group">
                <label asp-for="LinkedInProvider.ApplicationName" class="control-label"></label>
                <input asp-for="LinkedInProvider.ApplicationName" class="form-control" />
                <span asp-validation-for="LinkedInProvider.ApplicationName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.ClientId" class="control-label"></label>
                <input asp-for="LinkedInProvider.ClientId" class="form-control" />
                <span asp-validation-for="LinkedInProvider.ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.ClientSecret" class="control-label"></label>
                <input asp-for="LinkedInProvider.ClientSecret" class="form-control" />
                <span asp-validation-for="LinkedInProvider.ClientSecret" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.AuthorizationEndpoint" class="control-label"></label>
                <input asp-for="LinkedInProvider.AuthorizationEndpoint" class="form-control" />
                <span asp-validation-for="LinkedInProvider.AuthorizationEndpoint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.TokenEndpoint" class="control-label"></label>
                <input asp-for="LinkedInProvider.TokenEndpoint" class="form-control" />
                <span asp-validation-for="LinkedInProvider.TokenEndpoint" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LinkedInProvider.Scope" class="control-label"></label>
                <input asp-for="LinkedInProvider.Scope" class="form-control" />
                <span asp-validation-for="LinkedInProvider.Scope" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="LinkedInProvider.IsActive" /> @Html.DisplayNameFor(model => model.LinkedInProvider.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SAWebHost/Pages/Applications/Index.cshtml
@page
@model SAWebHost.Pages.Applications.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LinkedInProvider[0].ApplicationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LinkedInProvider[0].ClientId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LinkedInProvider[0].Scope)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LinkedInProvider[0].IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.LinkedInProvider) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Scope)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>