src/SAWebHost/Controllers/TokensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data;
using SAWebHost.Data.Dto;

namespace SAWebHost.Controllers
{
    //[Authorize]
    [Route("api/[controller]")]
    [ApiController]
    [Authorize("JwtBearer")]
    public class TokensController : ControllerBase
    {
        private readonly TokenRegistryContext _context;

        public TokensController(TokenRegistryContext context)
        {
            _context = context;
        }

        // GET: api/Tokens
        [HttpGet]
        public async Task<ActionResult<IEnumerable<AccessTokenEntry>>> GetAccessTokenEntry()
        {
            return await _context.AccessTokenEntry.ToListAsync();
        }

        // GET: api/Tokens/5
        [HttpGet("{id}")]
        public async Task<ActionResult<AccessTokenEntry>> GetAccessTokenEntry(string id)
        {
            var accessTokenEntry = await _context.AccessTokenEntry.FindAsync(id);

            if (accessTokenEntry == null)
            {
                return NotFound();
            }

            return accessTokenEntry;
        }

        // PUT: api/Tokens/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutAccessTokenEntry(string id, AccessTokenEntry accessTokenEntry)
        {
            if (id != accessTokenEntry.Id)
            {
                return BadRequest();
            }

            _context.Entry(accessTokenEntry).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AccessTokenEntryExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Tokens
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<AccessTokenEntry>> PostAccessTokenEntry(AccessTokenEntry accessTokenEntry)
        {
            _context.AccessTokenEntry.Add(accessTokenEntry);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateException)
            {
                if (AccessTokenEntryExists(accessTokenEntry.Id))
                {
                    return Conflict();
                }
                else
                {
                    throw;
                }
            }

            return CreatedAtAction("GetAccessTokenEntry", new { id = accessTokenEntry.Id }, accessTokenEntry);
        }

        // DELETE: api/Tokens/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteAccessTokenEntry(string id)
        {
            var accessTokenEntry = await _context.AccessTokenEntry.FindAsync(id);
            if (accessTokenEntry == null)
            {
                return NotFound();
            }

            _context.AccessTokenEntry.Remove(accessTokenEntry);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool AccessTokenEntryExists(string id)
        {
            return _context.AccessTokenEntry.Any(e => e.Id == id);
        }
    }
}

src/SAWebHost/Pages/Applications/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LinkedInApiClient;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Applications
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public CreateModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            LinkedInProvider = new LinkedInProvider
            {
                Id = IdGenerator.GetOne("app", Guid.NewGuid())
            };

            return Page();
        }

        [BindProperty]
        public LinkedInProvider LinkedInProvider { get; set; }


        public IActionResult OnPostUseLinkedInSettings()
        {
            if (!ModelState.IsValid)
            {
                ModelState.Clear();
            }

            LinkedInProvider = new LinkedInProvider
            {
                ApplicationName = LinkedInProvider.ApplicationName,
                Id = LinkedInProvider.Id,
                IsActive = LinkedInProvider.IsActive,
                ClientId = LinkedInProvider.ClientId,
                ClientSecret = LinkedInProvider.ClientSecret,
                AuthorizationEndpoint = LinkedInConstants.DefaultAuthorizationEndpoint,
                TokenEndpoint = LinkedInConstants.DefaultTokenEndpoint,
                Scope = "r_organization_social r_1st_connections_size r_ads_reporting rw_organization_admin r_basicprofile r_ads"
            };

            return Page();
        }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.LinkedInProvider.Add(LinkedInProvider);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

src/SAWebHost/Pages/Applications/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Applications
{
    [Authorize]
    public class DeleteModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public DeleteModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        [BindProperty]
        public LinkedInProvider LinkedInProvider { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            LinkedInProvider = await _context.LinkedInProvider.FirstOrDefaultAsync(m => m.Id == id);

            if (LinkedInProvider == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            LinkedInProvider = await _context.LinkedInProvider.FindAsync(id);

            if (LinkedInProvider != null)
            {
                _context.LinkedInProvider.Remove(LinkedInProvider);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

src/SAWebHost/Pages/Applications/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Applications
{
    public class DetailsModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public DetailsModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        public LinkedInProvider LinkedInProvider { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            LinkedInProvider = await _context.LinkedInProvider.FirstOrDefaultAsync(m => m.Id == id);

            if (LinkedInProvider == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

src/SAWebHost/Pages/Applications/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Applications
{
    [Authorize]
    public class EditModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public EditModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        [BindProperty]
        public LinkedInProvider LinkedInProvider { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            LinkedInProvider = await _context.LinkedInProvider.FirstOrDefaultAsync(m => m.Id == id);

            if (LinkedInProvider == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(LinkedInProvider).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LinkedInProviderExists(LinkedInProvider.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool LinkedInProviderExists(string id)
        {
            return _context.LinkedInProvider.Any(e => e.Id == id);
        }
    }
}

src/SAWebHost/Pages/Organizations/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Organizations
{
    public record TableOption
    {
        public int MyProperty { get; set; }
    }

    public class CreateModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public CreateModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            Organization = new Organization
            {
                Id = IdGenerator.GetOne("organization", Guid.NewGuid())
            };

            return Page();
        }

        [BindProperty]
        public Organization Organization { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Organization.Add(Organization);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

src/SAWebHost/Pages/Tokens/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using IdentityModel.Client;
using LinkedInApiClient.Authentication;
using LinkedInApiClient.Types;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using SAWebHost.Data;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Tokens
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly TokenRegistryContext context;
        private readonly LinkedInOptions options;
        private readonly UserManager<ApplicationUser> userManager;

        public CreateModel(TokenRegistryContext context, IOptionsMonitor<LinkedInOptions> options, UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
            this.options = options.CurrentValue;
            this.context = context;
        }

        public async Task<IActionResult> OnGetAsync(string code = null, string state = null)
        {
            var user = await userManager.GetUserAsync(User);

            ApplicationOptions = new SelectList(context.LinkedInProvider, nameof(LinkedInProvider.Id), nameof(LinkedInProvider.ApplicationName));
            OrganizationOptions = new SelectList(context.Organization, nameof(Organization.Id), nameof(Organization.Name));

            if (!string.IsNullOrEmpty(code))
            {
                var client = new HttpClient();

                LinkedInProvider provider = GetProvider(state);

                var response = await client.RequestAuthorizationCodeTokenAsync(new AuthorizationCodeTokenRequest
                {
                    Address = provider.TokenEndpoint,
                    ClientId = provider.ClientId,
                    ClientSecret = provider.ClientSecret,
                    RedirectUri = Url.PageLink("/Tokens/Create"),
                    Resource = provider.Scope.Split(" "),
                    Code = code
                });

                AccessTokenEntry = new AccessTokenEntry
                {
                    Id = IdGenerator.GetOne("token", Guid.NewGuid()),
                    OrganizationId = user.OrganizationUrn,
                    ProviderId = provider.Id,
                    CreatedOn = DateTimeOffset.Now,
                    AccessToken = response.AccessToken,
                    ExpiresIn = response.ExpiresIn,
                    RefreshToken = response.RefreshToken,
                    RefreshTokenExpiresIn = response.Json.GetProperty("refresh_token_expires_in").GetInt32()
                };
            }
            else
            {
                AccessTokenEntry = new AccessTokenEntry
                {
                    Id = IdGenerator.GetOne("token", Guid.NewGuid()),
                    CreatedOn = DateTimeOffset.Now,
                    OrganizationId = user.OrganizationUrn,
                };
            }

            return Page();
        }

        private LinkedInProvider GetProvider(string state)
        {
            if (!string.IsNullOrEmpty(state))
            {
                var providerId = LinkedInURN.Parse(Encoding.UTF8.GetString(Convert.FromBase64String(state)));
                return context.LinkedInProvider.Find(providerId.ToString());
            }

            return null;
        }

        [BindProperty]
        public AccessTokenEntry AccessTokenEntry { get; set; }

        public SelectList ApplicationOptions { get; set; }

        public SelectList OrganizationOptions { get; set; }


        public async Task<IActionResult> OnPostConnectAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var provider = await context.LinkedInProvider.FindAsync(AccessTokenEntry.ProviderId);
            var query = new LinkedInApiClient.Types.Parameters
            {
                ["response_type"] = "code",
                ["client_id"] = provider.ClientId,
                ["redirect_uri"] = Url.PageLink("/Tokens/Create"),
                ["state"] = Convert.ToBase64String(Encoding.UTF8.GetBytes(provider.Id)),
                ["scope"] = provider.Scope
            };

            return Redirect(query.ToUrlQueryString(provider.AuthorizationEndpoint));
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            context.AccessTokenEntry.Add(AccessTokenEntry);
            await context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

src/SAWebHost/Pages/Tokens/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SAWebHost.Data.Dto;

namespace SAWebHost.Pages.Tokens
{
    public class IndexModel : PageModel
    {
        private readonly SAWebHost.Data.TokenRegistryContext _context;

        public IndexModel(SAWebHost.Data.TokenRegistryContext context)
        {
            _context = context;
        }

        public IList<AccessTokenEntry> AccessTokenEntry { get;set; }

        public async Task OnGetAsync()
        {
            AccessTokenEntry = await _context.AccessTokenEntry.ToListAsync();
        }
    }
}

src/SAWebHost/Pages/Tokens/Create.cshtml
@page
@model SAWebHost.Pages.Tokens.CreateModel
@inject UserManager<ApplicationUser> userManager

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>AccessTokenEntry</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AccessTokenEntry.Id" class="control-label"></label>
                <input asp-for="AccessTokenEntry.Id" class="form-control" readonly />
                <span asp-validation-for="AccessTokenEntry.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccessTokenEntry.OrganizationId" class="control-label"></label>
                <select asp-for="AccessTokenEntry.OrganizationId" class ="form-control" asp-items="Model.OrganizationOptions"></select>
            </div>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Access Tokens</h5>
                    <div class="card-text">
                        <div class="form-group">
                        </div>
                        <div class="form-group">
                            <label asp-for="AccessTokenEntry.ProviderId" class="control-label"></label>
                            <select asp-for="AccessTokenEntry.ProviderId" class ="form-control" asp-items="Model.ApplicationOptions"></select>
                        </div>
                        <div class="form-group">
                            <label asp-for="AccessTokenEntry.AccessToken" class="control-label"></label>
                            <input asp-for="AccessTokenEntry.AccessToken" class="form-control" />
                            <span asp-validation-for="AccessTokenEntry.AccessToken" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AccessTokenEntry.ExpiresIn" class="control-label"></label>
                            <input asp-for="AccessTokenEntry.ExpiresIn" class="form-control" />
                            <span asp-validation-for="AccessTokenEntry.ExpiresIn" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AccessTokenEntry.RefreshToken" class="control-label"></label>
                            <input asp-for="AccessTokenEntry.RefreshToken" class="form-control" />
                            <span asp-validation-for="AccessTokenEntry.RefreshToken" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AccessTokenEntry.RefreshTokenExpiresIn" class="control-label"></label>
                            <input asp-for="AccessTokenEntry.RefreshTokenExpiresIn" class="form-control" />
                            <span asp-validation-for="AccessTokenEntry.RefreshTokenExpiresIn" class="text-danger"></span>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-secondary" asp-page-handler="Connect">Connect</button>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="AccessTokenEntry.CreatedOn" class="control-label"></label>
                <input asp-for="AccessTokenEntry.CreatedOn" class="form-control" readonly />
                <span asp-validation-for="AccessTokenEntry.CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SAWebHost/Pages/Tokens/Delete.cshtml
@page
@model SAWebHost.Pages.Tokens.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AccessTokenEntry</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccessTokenEntry.AccessToken)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccessTokenEntry.AccessToken)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccessTokenEntry.ExpiresIn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccessTokenEntry.ExpiresIn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccessTokenEntry.RefreshToken)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccessTokenEntry.RefreshToken)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccessTokenEntry.RefreshTokenExpiresIn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccessTokenEntry.RefreshTokenExpiresIn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccessTokenEntry.CreatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccessTokenEntry.CreatedOn)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="AccessTokenEntry.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

src/SAWebHost/Pages/Tokens/Details.cshtml
@page "{id}"
@model SAWebHost.Pages.Tokens.DetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>AccessTokenEntry</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccessTokenEntry.AccessToken)
        </dt>
        <dd class="col-sm-10">
            <textarea asp-for="AccessTokenEntry.AccessToken" style="width:100%" rows="5"></textarea>            
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccessTokenEntry.ExpiresIn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccessTokenEntry.ExpiresIn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccessTokenEntry.RefreshToken)
        </dt>
        <dd class="col-sm-10">
            <textarea asp-for="AccessTokenEntry.RefreshToken" style="width:100%" rows="5"></textarea>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccessTokenEntry.RefreshTokenExpiresIn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccessTokenEntry.RefreshTokenExpiresIn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccessTokenEntry.CreatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccessTokenEntry.CreatedOn)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.AccessTokenEntry.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

src/SAWebHost/Pages/Tokens/Edit.cshtml
@page
@model SAWebHost.Pages.Tokens.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>AccessTokenEntry</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AccessTokenEntry.Id" />
            <div class="form-group">
                <label asp-for="AccessTokenEntry.ProviderId" class="control-label"></label>
                <select asp-for="AccessTokenEntry.ProviderId" class ="form-control" asp-items="Model.ApplicationOptions"></select>
            </div>
            <div class="form-group">
                <label asp-for="AccessTokenEntry.OrganizationId" class="control-label"></label>
                <select asp-for="AccessTokenEntry.OrganizationId" class="form-control" asp-items="Model.OrganizationOptions"></select>
                <span asp-validation-for="AccessTokenEntry.OrganizationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccessTokenEntry.AccessToken" class="control-label"></label>
                <input asp-for="AccessTokenEntry.AccessToken" class="form-control" />
                <span asp-validation-for="AccessTokenEntry.AccessToken" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccessTokenEntry.ExpiresIn" class="control-label"></label>
                <input asp-for="AccessTokenEntry.ExpiresIn" class="form-control" />
                <span asp-validation-for="AccessTokenEntry.ExpiresIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccessTokenEntry.RefreshToken" class="control-label"></label>
                <input asp-for="AccessTokenEntry.RefreshToken" class="form-control" />
                <span asp-validation-for="AccessTokenEntry.RefreshToken" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccessTokenEntry.RefreshTokenExpiresIn" class="control-label"></label>
                <input asp-for="AccessTokenEntry.RefreshTokenExpiresIn" class="form-control" />
                <span asp-validation-for="AccessTokenEntry.RefreshTokenExpiresIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccessTokenEntry.CreatedOn" class="control-label"></label>
                <input asp-for="AccessTokenEntry.CreatedOn" class="form-control" />
                <span asp-validation-for="AccessTokenEntry.CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SAWebHost/Pages/Tokens/Index.cshtml
@page
@model SAWebHost.Pages.Tokens.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AccessTokenEntry[0].AccessToken)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccessTokenEntry[0].ExpiresIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccessTokenEntry[0].RefreshTokenExpiresIn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccessTokenEntry[0].CreatedOn)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.AccessTokenEntry) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                <span>@((item.CreatedOn.AddSeconds(item.ExpiresIn) - DateTimeOffset.Now).ToString(@"dd\.hh\:mm\:ss"))</span>
            </td>
            <td>
                <span>@((item.CreatedOn.AddSeconds(item.RefreshTokenExpiresIn) - DateTimeOffset.Now).ToString(@"dd\.hh\:mm\:ss"))</span>                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>